### ISSUE TITLE
Service not accessible 

### ISSUE THREAD

**Issue by huang-xx** [haozibi/leetcode-badge#1]
![image](https://user-images.githubusercontent.com/10807108/120668362-fc43d180-c4c0-11eb-9da6-bf4d39178e30.png)

Hello, I have been using your service for several months. Thanks for your work! By embedding your service into [Notion](https://www.notion.so/), I can visually observe my progress. But today, your service is no longer accessible, could you please fix it? 

And you should accept donations on your project homepage.

**Comment by haozibi** [comment]
Sorry, I forgot to update the https certificate before, I will update it regularly in the future, sorry

**Comment by haozibi** [comment]
@huang-xx u can try   `https://leetcode-badge.haozibi.dev/v1cn/chart/submission-calendar/{LeetCode_ID}.svg`
