### ISSUE TITLE
题目总数好像不正确

### ISSUE THREAD

**Issue by cloydlau** [haozibi/leetcode-badge#3]
你好，截至目前，题目总数应为2497道（中国区），不知道2637这个数字怎么来的

**Comment by haozibi** [comment]
你好，非常抱歉，才看到

2497 是从哪里看到的？

**Comment by haozibi** [comment]
我好像知道了，等我有时间我会 fix 的

**Comment by haozibi** [comment]
新增加了卡片模式，这个数据和官网显示是一致的，推荐使用

https://github.com/haozibi/leetcode-badge#%E5%8D%A1%E7%89%87

**Comment by haozibi** [comment]
原有「徽标」不准备更新了，推荐使用 卡片 模式

**Comment by cloydlau** [comment]
你好，请问是否可以选择语言，比如追加参数 `?lang=en`，那么“解题数量”、“解决问题”、“简单”、“中等”、“困难”就变成英文了。看了下你的源码是用的 Go，我不是写 Go 的，要不然我都提 PR 了

**Comment by haozibi** [comment]
「就变成英文了」是文字从中文变英文？还是区分 「国外」、「国内」的 leetcode 站点？

**Comment by cloydlau** [comment]
感谢回复。仅文字，之所以提这个事情还有一个原因是这个卡片本身的语言也有点不统一，`'s` 是一个英文语法：

![image](https://user-images.githubusercontent.com/31238760/191431062-d6e3c8d1-b2e6-497a-a757-a91a6ca8f6d5.png)

或者就直接默认为英文也可以，文案就统一了

**Comment by cloydlau** [comment]
如果你觉得直接默认为英文 ok 的话，我可以提 PR 修改，加参数的方式我确实因为没用过 Go 可能搞不定。

**Comment by haozibi** [comment]
这个我今天加一下就好

**Comment by cloydlau** [comment]
感谢大佬，这个卡片挺好用的，我用在首页很久了

**Comment by haozibi** [comment]
已经更新了 https://leetcode-badge.haozibi.dev/v1cn/card/question-process/haozibi.svg?lang=en  ![](https://leetcode-badge.haozibi.dev/v1cn/card/question-process/haozibi.svg?lang=en)

**Comment by haozibi** [comment]
如果有其他问题，请重新开一个新 issue

**Comment by cloydlau** [comment]
神速，强无敌
