### ISSUE TITLE
用户名中带中划线 - 的获取不到  user not found

### ISSUE THREAD

**Issue by muyanshouji** [haozibi/leetcode-badge#5]
您好！ 
用户名中带中划线 - 的获取不到  user not found 
![image](https://user-images.githubusercontent.com/55934984/196462392-1c38f813-60de-471c-bd40-7180db3f032a.png)

**Comment by haozibi** [comment]
能提供一下具体的名称么？

**Comment by muyanshouji** [comment]
[mr-j001](https://leetcode.cn/u/mr-j001/) 这个

**Comment by muyanshouji** [comment]
> 能提供一下具体的名称么？
[mr-j001](https://leetcode.cn/u/mr-j001/) 这个

**Comment by haozibi** [comment]
中国区还是国外的用户？

你可以把问题描述的清晰一点，节约一下时间

**Comment by muyanshouji** [comment]
> 中国区还是国外的用户？
> 
> 你可以把问题描述的清晰一点，节约一下时间

中国区啊，引用我上面发的 用户名进行替换 usr not found

**Comment by muyanshouji** [comment]
> 
还需要其他描述么

**Comment by haozibi** [comment]
已经修复了
![](https://leetcode-badge.haozibi.dev/v1cn/mr-j001.svg)
![](https://leetcode-badge.haozibi.dev/v1cn/ranking/mr-j001.svg)
![](https://leetcode-badge.haozibi.dev/v1cn/card/contest-ranking/mr-j001.svg)

**Comment by muyanshouji** [comment]
非常感谢
